### PR TITLE
Fix yaml load issue and Safari mistake

### LINKED ISSUE #49: Psych::BadAlias (Unknown alias: iphone_default)
```ruby
$ irb
2.6.3 :001 > require 'webdriver-user-agent'
 => true
2.6.3 :002 > driver = Webdriver::UserAgent.driver(:browser => :safari, :agent => :iphone, :orientation => :landscape)
2021-05-18 12:27:13.242 defaults[71288:4173580]
Domain (com.apple.Safari) not found.
Defaults have not been changed.
2021-05-18 12:27:13.301 defaults[71289:4173584]
Domain (com.apple.Safari) not found.
Defaults have not been changed.
Traceback (most recent call last):
       16: from /Users/sam/.rvm/gems/ruby-2.6.3/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:343:in `revive_hash'
       15: from /Users/sam/.rvm/gems/ruby-2.6.3/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:343:in `each_slice'
       14: from /Users/sam/.rvm/gems/ruby-2.6.3/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:343:in `each'
       13: from /Users/sam/.rvm/gems/ruby-2.6.3/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
       12: from /Users/sam/.rvm/gems/ruby-2.6.3/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:35:in `accept'
       11: from /Users/sam/.rvm/gems/ruby-2.6.3/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:6:in `accept'
       10: from /Users/sam/.rvm/gems/ruby-2.6.3/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:30:in `visit'
        9: from /Users/sam/.rvm/gems/ruby-2.6.3/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
        8: from /Users/sam/.rvm/gems/ruby-2.6.3/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:343:in `revive_hash'
        7: from /Users/sam/.rvm/gems/ruby-2.6.3/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:343:in `each_slice'
        6: from /Users/sam/.rvm/gems/ruby-2.6.3/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:343:in `each'
        5: from /Users/sam/.rvm/gems/ruby-2.6.3/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
        4: from /Users/sam/.rvm/gems/ruby-2.6.3/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:35:in `accept'
        3: from /Users/sam/.rvm/gems/ruby-2.6.3/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:6:in `accept'
        2: from /Users/sam/.rvm/gems/ruby-2.6.3/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:30:in `visit'
        1: from /Users/sam/.rvm/gems/ruby-2.6.3/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:430:in `visit_Psych_Nodes_Alias'
Psych::BadAlias (Unknown alias: iphone_default)
```

### LINKED ISSUE #50: Logical fault with Safari config
`Driver` code for the `for` function erases the changes made by it for Safari useragent string and language preferences.

```ruby
      ensure
        if safari?(opts)
          case
          when opts[:safari_technology_preview].is_a?(TrueClass)
            `defaults delete com.apple.SafariTechnologyPreview CustomUserAgent`
            `defaults delete com.apple.SafariTechnologyPreview AppleLanguages`
          else
            `defaults delete com.apple.Safari CustomUserAgent`
            `defaults delete com.apple.Safari AppleLanguages`
          end
        end
      end
```

### PR DESCRIPTION
**Pull request by samnissen**
- Fixes #49 
- Fixes #50 
- Makes tests for #51 pending

### CODE REVIEW

File: lib/webdriver-user-agent/core_ext/hash.rb [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+  def alias_hash_deep_symbolize_keys!(h)
+    h.keys.each do |k|
+      ks    = k.respond_to?(:to_sym) ? k.to_sym : k
+      h[ks] = h.delete k
+      alias_hash_deep_symbolize_keys! h[ks] if h[ks].kind_of? Hash
+    end
+    
+    h
+  end # https://stackoverflow.com/a/8379653/1651458
+end
```
Comment (sandeepnagra) [inline lib/webdriver-user-agent/core_ext/hash.rb:32]: Add newline at end of file

**Review by sandeepnagra — APPROVED** [review]
Overall it looks good to me, just a very minor comment.
